Dz1
xayliot/2024-2-VK-EDU-Frontend-A-Kim pull request #1
Opened 2024-09-23 17:57 UTC by xayliot

# Домашнее задание №1

Прошу @kgrechin или @sh4rkizz проверить его.

Что было сделано:
-были написаны функции: проверки предложения на корректность, перевод байтов, вывод неуникальных значений
-для перевода байтов были также написаны тесты для проверки корректности работы функции

2024-09-23 18:29 UTC, sh4rkizz requested changes
Еще надо в асинги/ревьюеры/теги докинуть преподов

2024-09-23 18:29 UTC, sh4rkizz commented on nonUniqueElements.js
> +  return nonUniq
Использование второго массива ничем не обусловлено, попробуй воспользоваться встроенными инструментами фильтрации и применить их к исходному массиву

2024-09-23 18:29 UTC, sh4rkizz commented on convertBytesToHuman.js
> +    return "false"
ожидаем на выходе нестроковый false

2024-09-26 09:59 UTC, sh4rkizz requested changes

2024-09-26 09:59 UTC, sh4rkizz commented on convertBytesToHuman.test.js
> +});
давай дополним список тестов другими невалидными сценариями
Infinity, () => {}, NaN и другие, гарантированно функция сложится на некоторых из них

2024-09-26 09:59 UTC, sh4rkizz commented on nonUniqueElements.js
> +}
это, конечно, не совсем то, о чем я говорил в комменте, но за однострочник - лайк, красивое

попробуй оставить применение мапки, но при этом не использовать дополнительный массив, а фильтровать исходных

2024-09-26 09:59 UTC, sh4rkizz commented on convertBytesToHuman.js
> +  } else {
else в целом не нужен здесь, если провалится в if, функция прекратит выполнение до попадания в цикл

2024-09-26 13:48 UTC, sh4rkizz approved these changes
lgtm

2024-09-26 13:48 UTC, sh4rkizz commented
@HaseProgram

2024-10-01 21:34 UTC, HaseProgram approved these changes
12!

2024-10-01 21:35 UTC, merged