ДЗ3
xayliot/2024-2-VK-EDU-Frontend-A-Kim pull request #3
Opened 2024-10-10 21:35 UTC by xayliot

Домашнее задание №3

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz .

Что было сделано:
* страница с чатами
* разбиение на компоненты 
* сохранение историй чатов

p.s совсем пустышку заливать не хотел, чтобы попасть по срокам, поэтому просрочил

2024-10-10 21:37 UTC, xayliot commented
основной функционал работает, осталось только порядок навести, а так чаты создаются, сохраняются, и наполненеие всех чатов сохраняется

2024-10-13 09:24 UTC, sh4rkizz commented
Закинул git-diff с более корректными настройками в личку

2024-10-21 21:38 UTC, sh4rkizz commented
Не хватает <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no"> на странице списка чатов

2024-10-21 21:48 UTC, sh4rkizz commented
При отправке длинного сообщения появляется горизонтальный скролл
<img width="410" alt="изображение" src="https://github.com/user-attachments/assets/d29e40e1-5e8b-450d-8890-71acdda41220">

2024-10-21 21:52 UTC, sh4rkizz commented
На мобильных разрешениях себя очень странно чувствуют шрифты, нужно как-то поправить
<img width="455" alt="изображение" src="https://github.com/user-attachments/assets/65a4a42f-7322-4333-87e2-9b1dbc0b60ac">

2024-10-21 21:52 UTC, sh4rkizz requested changes
Давай поправим в рамках третьей, что отписано в этом ПР

2024-10-23 17:43 UTC, martinkomitsky commented
@sh4rkizz тогда это апрув?

2024-10-23 20:46 UTC, sh4rkizz approved these changes
lgtm [поправили в МРе 4ой]

2024-10-27 16:28 UTC, merged

2024-10-27 16:28 UTC, martinkomitsky commented
7