Dz4
xayliot/2024-2-VK-EDU-Frontend-A-Kim pull request #4
Opened 2024-10-21 17:24 UTC by xayliot

# Домашнее задание №4

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:
добавлена анимация при наведении на чат
добавлена анимация отрисовки сообщений, а также при добавлении нового сообщения
улучшен визуал: подкорректирован размер шрифтов, размер сообщения по размеру текста

2024-10-21 21:46 UTC, sh4rkizz commented
### Задание на 4

1. Убрать автокомплит формы
<img width="974" alt="изображение" src="https://github.com/user-attachments/assets/ffca590c-fed9-41cb-8078-f6392947fbc4">

2. Улучшение блочной верстки:
- font-size времени отправки не должен быть больше текста сообщения
- стоит отлепить от верхнего края автора сообщения
- предлагаю отказаться от треугольничка справа и уменьшить толщину border до 0.5px
- а вместо треугольничка более чистым решением для правого блока будет `border-radius: 10px 10px 0 10px;`, соответственно для левого `border-radius: 0 10px 10px 10px;`
<img width="390" alt="изображение" src="https://github.com/user-attachments/assets/a93f22e9-b221-4159-b7c8-ec4a73851353">

3. Цвет ховера стоит выбрать помягче)
<img width="424" alt="изображение" src="https://github.com/user-attachments/assets/4c06a2a5-4f11-4c2f-a7ee-8e639704bec6">


4. Предлагаю немного уменьшить хедер, уж очень он большой какой-то
5. Нужно проработать ховеры на кнопках, хотя бы простое изменение цвета [не на всех сделано]

### Доп. задание для 4 ДЗ:
- Нужно проработать доступность, чтобы можно было все кнопки обойти с помощью `TAB` [сверху-вниз, слева-направо]
- Каждая кнопка должна иметь outline при фокусе с клавиатуры, при этом не обязательно его отображать на клик [не используй обычный `:focus {}`]
- Ссылку и кнопку нельзя использовать как один компонент, button здесь не нужен [при этом стиль фокуса клавиатурой этой `<a>` и остальных `<button>` отличаться не должен]
<img width="400" alt="изображение" src="https://github.com/user-attachments/assets/dd85a6bc-405c-4fab-9511-4f4763dd3137">
- Фокус должен так же показываться на форме и кнопке отправки сообщения, а также на каждом сообщении из списка чатов [тк это ссылки]
- Некликабельные элементы [сообщение, аватарка и пр.] НЕ должны иметь состояние фокуса, если какой-то .html элемент приобретает это состояние, его можно убрать с помощью `tabindex="-1"`

2024-10-21 21:53 UTC, sh4rkizz requested changes
Доп задание + рекомендации по доработке в рамках 4 ДЗ - выше

2024-10-26 09:08 UTC, sh4rkizz commented
Не хватает ховеров на кнопках [всех]
![изображение](https://github.com/user-attachments/assets/1ddb15fb-b9ea-440d-8cc0-295f7d28d0f5)

2024-10-26 09:12 UTC, sh4rkizz commented
Странная кликабельная область, давай починим)
![изображение](https://github.com/user-attachments/assets/b1408222-29c0-4d32-9246-a4249784ee95)

2024-10-26 09:12 UTC, sh4rkizz commented
кажется что перестала работать эта кнопочка 
![изображение](https://github.com/user-attachments/assets/8cc96364-680f-4c3d-95da-477f6e1609d0)

2024-10-26 09:14 UTC, sh4rkizz commented
предлагаю для текста сделать шрифты 
`16px` для десктопа
`14px` для мобилки
![изображение](https://github.com/user-attachments/assets/9a157e80-2be2-4e5c-9be9-7d9a661efb34)

2024-10-26 09:15 UTC, sh4rkizz commented
сообщения странным образом стали залезать на шапку чатика

![изображение](https://github.com/user-attachments/assets/5862f03b-755c-4644-b7ab-6467662a9e02)

2024-10-28 16:40 UTC, sh4rkizz submitted a review, later dismissed
lgtm

2024-10-28 18:22 UTC, sh4rkizz approved these changes
lgtm

2024-10-31 06:30 UTC, HaseProgram approved these changes
7!

2024-10-31 06:31 UTC, merged