Dz5
xayliot/2024-2-VK-EDU-Frontend-A-Kim pull request #5
Opened 2024-11-03 15:29 UTC by xayliot

# Домашнее задание №5

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz .

Что было сделано:
перенос проекта на react
разбиение проекта на большее количество компонентов для более удобной работы с ними

2024-11-07 20:50 UTC, sh4rkizz requested changes

2024-11-07 20:50 UTC, sh4rkizz commented on react-chat/src/components/ChatModal/index.jsx
> +                <h2>Создать новый чат</h2>
требую выровнять плюсики

<img width="160" alt="изображение" src="https://github.com/user-attachments/assets/7b544920-27ab-4cb0-86be-31ff8826b99e">

2024-11-07 20:50 UTC, sh4rkizz commented on react-chat/public/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1" />
забыт запрет пользовательского змма

2024-11-07 20:50 UTC, sh4rkizz commented on react-chat/public/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1" />
считаю стоит уменьшить размеры картинок и хедера для мобилки

<img width="450" alt="изображение" src="https://github.com/user-attachments/assets/02e0ff4c-2228-4bd6-b79f-a086e476abed">

2024-11-07 20:50 UTC, sh4rkizz commented on react-chat/public/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1" />
давай починим [уберем] скролл при длинных именах
в хедере и списке чатов

<img width="927" alt="изображение" src="https://github.com/user-attachments/assets/409a58bf-214a-4b1b-8a37-a42de34de9e1">

<img width="560" alt="изображение" src="https://github.com/user-attachments/assets/15615d53-b481-43a8-acf1-897be838b4ed">

2024-11-07 20:50 UTC, sh4rkizz commented on react-chat/public/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1" />
обрезать длинные сообщения лучше многоточием

<img width="508" alt="изображение" src="https://github.com/user-attachments/assets/38137c99-9cc0-42fc-a25e-9ffda6c15df2">

2024-11-07 20:50 UTC, sh4rkizz commented on react-chat/src/components/ChatModal/index.jsx
> +import './index.scss';
крайне рекомендую ознакомиться и использовать `css-modules`
на 100% уберет пересечение названия стилей при подгрузке в страницу

2024-11-07 20:50 UTC, sh4rkizz commented on react-chat/public/index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1" />
какой-то большой блок для такого маленького контента
посмотри, можно ли уменьшить пустое пространство, ничего не ломая

<img width="300" alt="изображение" src="https://github.com/user-attachments/assets/37917264-912a-433a-b8e0-470178ef764c">

2024-11-07 20:52 UTC, sh4rkizz commented
Предлагаю доп заданием с этой модалкой поработать [можно в 6-ой сделать]

<img width="897" alt="изображение" src="https://github.com/user-attachments/assets/b09e0a82-65d1-4a53-90de-abd35932a834">

- закрытие на Escape
- закрытие на клик вне модалки
- автофокус на первое поле
<img width="324" alt="изображение" src="https://github.com/user-attachments/assets/a58b12cc-ae95-4c99-be2e-9e6deb0f3bd5">
- как-нибудь выровнять стили

2024-11-10 20:34 UTC, sh4rkizz requested changes

2024-11-10 20:34 UTC, sh4rkizz commented on react-chat/src/components/ChatModal/index.jsx
> +import './index.scss';
нехорошо, что кнопка создания чата не ездит вместе с экраном, а остается на том же месте 
[попробуй создать больше чатов, чтобы можно было скроллить список чатов, поймешь о чем я]

<img width="316" alt="изображение" src="https://github.com/user-attachments/assets/20cdbef1-e5cf-4b5f-bb5d-ed629fd5198b">

2024-11-10 20:35 UTC, sh4rkizz commented
Скролл горизонтальных бы поправить еще 

<img width="706" alt="изображение" src="https://github.com/user-attachments/assets/e5f2198a-4939-49e4-a0c5-2b1609c33cf8">

2024-11-10 20:37 UTC, sh4rkizz approved these changes
lgtm, последние комменты поправишь в 6-ой

2024-11-15 09:54 UTC, martinkomitsky commented
10

2024-11-15 09:54 UTC, merged