Dz6
xayliot/2024-2-VK-EDU-Frontend-A-Kim pull request #6
Opened 2024-11-17 15:03 UTC by xayliot

# Домашнее задание №6

Прошу  @haseprogram, @kgrechin или @sh4rkizz  проверить его.

Что было сделано:
переход по страницам с помощью hashrouter
страница пользователя
исправлен стиль кнопки, она больше не уезжает при большом количетстве чатов

2024-11-18 20:05 UTC, sh4rkizz requested changes

2024-11-18 20:05 UTC, sh4rkizz commented on react-chat/src/App.js
> +            <Route path="/profile" element={<PageProfile onBack={() => window.history.back()} />} />
Не до конца понимаю, для чего вам рекомендовали делать передавая внутрь onBack
Никто не мешает сделать так

```
<Route path="/" element={<PageChatList />} />
<Route path="/chat/:chatId" element={<PageChat />
<Route path="/profile" element={<PageProfile />
```

А на каждой странице уже обрабатывать хейдлер кнопки назад 
```
const handleGoBack = () => {
    window.history.back()
}
```

2024-11-18 20:05 UTC, sh4rkizz commented on react-chat/src/App.js
> +            <Route path="/profile" element={<PageProfile onBack={() => window.history.back()} />} />
Давай добавим 404 страницу, которая будет по умолчанию показываться, если URL не соответствует ни одному из паттернов

2024-11-18 20:05 UTC, sh4rkizz commented on react-chat/src/pages/PageChatList/index.jsx
> +    };
Большого смысла в использовании navigate нет, корректнее будет сделать сам компонент чата ссылкой
Пользователи скринридера скажут за такое спасибо

2024-11-18 20:05 UTC, sh4rkizz commented on react-chat/src/pages/PageChatList/index.jsx
> +    };
Аналогично про компонент-ссылку

2024-11-18 20:05 UTC, sh4rkizz commented on react-chat/src/pages/PageProfile/index.jsx
> +    }, []);
Крайне советую пользоваться подобной штукой
Позволит тебе сильно сократить количество кода, упростит валидацию, нужно подогнать под твою реализацию

```
const [errors, setErrors] = useState({});
const [data, setData] = useState({});

const handleInputChange = (event) => {
    const name = event.target.name;
    const value = event.target.value;

    setError((prev) => ({ ...prev, [name]: null }));
    setData((prev) => ({ ...prev, [name]: value }));
}

const handleFileChange = (event) => {
    const file = e.target.files[0];
    setData((prev) => ({ ...prev, avatar: file }));
}
```

2024-11-18 20:05 UTC, sh4rkizz commented on react-chat/src/pages/PageProfile/index.jsx
> +    }, []);
Слишком маленькая кликабельная область на полях ввода

<img width="864" alt="изображение" src="https://github.com/user-attachments/assets/f9b15e08-349e-4234-a0ef-a75feb8c81ff">

<img width="503" alt="изображение" src="https://github.com/user-attachments/assets/6d64394e-7dad-494c-8346-1686dbaebd0e">

2024-11-18 20:05 UTC, sh4rkizz commented on react-chat/src/pages/PageProfile/index.jsx
> +    }, []);
Стоит поле full name разбить на 2 поля - имя и фамилия [first_name и last_name]
Дальше будет прикручиваться бекенд, где именно такое разделение

2024-11-18 20:05 UTC, sh4rkizz commented on react-chat/src/pages/PageProfile/index.jsx
> +    }, []);
Если требуешь от пользователя каких-то условий "корректности" ввода, стоит о них писать в подсказке ДО того, как он начал вбивать туда текст

<img width="478" alt="изображение" src="https://github.com/user-attachments/assets/2165cf78-0811-40d8-98e7-ed794b76121c">

2024-11-18 20:05 UTC, sh4rkizz commented on react-chat/src/pages/PageProfile/index.jsx
> +    }, []);
Хочется видеть индикацию того, что данные сохранились успешно 
[модалка / alert / текст на странице] - нечто появляющееся на 3-5 секунд

2024-11-18 20:05 UTC, sh4rkizz commented on react-chat/src/pages/PageProfile/index.jsx
> +    }, []);
Пользователю очень неудобно попадать в эту мишень чтобы подгрузить фотку, стоит увеличить [стандартный МИНИМУМ - 40x40 px]

<img width="466" alt="изображение" src="https://github.com/user-attachments/assets/88644d79-8410-45f0-8901-c012dd4affb6">

2024-11-21 08:08 UTC, sh4rkizz approved these changes
lgtm!

2024-11-26 22:01 UTC, HaseProgram commented
Аппрув! 10

2024-11-26 22:01 UTC, merged