Dz7
xayliot/2024-2-VK-EDU-Frontend-A-Kim pull request #7
Opened 2024-11-28 19:22 UTC by xayliot

# Домашнее задание №7

Прошу @martinkomitsky  или @sh4rkizz  проверить его.

Что было сделано:
страницы для регистрации и авторизации
смена логики получения и сохранения данных с локального хранилища на получение через API c бэка
расширение количества атрибутов у элементов для последующего расширения функционала

2024-11-30 13:46 UTC, sh4rkizz requested changes

2024-11-30 13:46 UTC, sh4rkizz commented on react-chat/src/pages/PageChatList/index.jsx
> +                setChats(response.data);
Это не тот урл, который отдает список чатов

2024-11-30 13:46 UTC, sh4rkizz commented on react-chat/src/pages/PageProfile/index.jsx
> +                const response = await axios.get('');
Нужно чтобы подтягивались данные профиля
Отсуствует урл для запроса

POST нигде тоже не обработан

2024-11-30 13:46 UTC, sh4rkizz commented on react-chat/src/pages/PageChatList/index.jsx
> +            const response = await axios.post('...',chatData);
Так же отсутствует урл для запроса

2024-11-30 13:46 UTC, sh4rkizz commented on react-chat/src/pages/PageChatList/index.jsx
> +            const response = await axios.post('...',chatData);
пусть страница не стилизована - ошиьки все равно надо писать контекстные
реальная ошибка - такой username уже используется

<img width="1440" alt="изображение" src="https://github.com/user-attachments/assets/3d0c4fbd-8a04-4bbb-ae41-04723a167b9b">

2024-12-08 09:47 UTC, sh4rkizz commented
Все еще не работает список чатов

![изображение](https://github.com/user-attachments/assets/d0d99fdf-df00-4a0e-a5bc-a139779b76ae)

А переход к чату что-то не то открывает
#/chat/count

2024-12-09 13:51 UTC, sh4rkizz commented
Сломан билд ghpages
```
[eslint] 
src/pages/PageChat/index.jsx
  Line 41:31:  'page' is not defined  no-undef
```

2025-01-04 13:19 UTC, merged

2025-01-23 10:22 UTC, martinkomitsky commented
7