Exam
xayliot/2024-2-VK-EDU-Frontend-A-Kim pull request #8
Opened 2024-12-23 18:29 UTC by xayliot

EXAM

- [ ] В корневой папке репозитория создать базовое приложение exam с помощью [CRA](https://github.com/facebook/create-react-app#quick-overview) (или vite) по инструкции выше
- [ ]  Сверстать 2 страницы и необходимые компоненты
- [ ]  Использовать стили. Дизайн должен быть похожим на макет
- [ ]  Реализовать перевод с одного языка на другой (нужно сделать так, чтобы можно было выбирать языки из выпадающего списка)
- [ ]  Реализовать перевод с неизвестного языка (автоопределитель из API)
- [ ]  Сохранять историю переводов в localStorage
- [ ]  Использовать Redux
- [ ]  Использовать React-router для перехода между страницами
- [ ]  Задеплоить решение, используя GitHub Actions
- [ ]  Ревью: получить правки по коду и исправить их (получаются лично у преподавателя и выполняются самостоятельно) [10 баллов]

2024-12-30 12:23 UTC, HaseProgram requested changes
Привет. Пока не работает базовый функционал, так как апи не прикруено. Отсюда не работает
1) Перевод
2) Автоперевод
3) История

Пока готов поставить 20 баллов, добавь апи, будует перепроверка)
По самому коду и кодстайлу вопросов нет

2024-12-30 12:23 UTC, HaseProgram commented on exam/src/translate.ts
> +        this.apiUrl = '';
хм

2024-12-31 17:15 UTC, xayliot commented on exam/src/translate.ts
> +        this.apiUrl = '';
фиксы будут сразу после нового года
кстати, с наступающим!!!

2025-01-04 13:19 UTC, HaseProgram approved these changes
Теперь хорошо) 46!

2025-01-04 13:19 UTC, merged